export const LOAD_HAR_CONTENT = 'LOAD_HAR_CONTENT'
export const LOAD_HAR_SUCCESS = 'LOAD_HAR_SUCCESS'
export const SHOW_HIDE_STATISTICS = 'SHOW_HIDE_STATISTICS'
export const LINK_GENERATE_REQUEST = 'LINK_GENERATE_REQUEST'
export const LINK_GENERATE_SUCCESS = 'LINK_GENERATE_SUCCESS'
export const LINK_GENERATE_FAILURE = 'LINK_GENERATE_FAILURE'

